services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Core\:
        resource: '../src/Core/*'
        exclude:
            - '../src/Core/Application/Service/GenerateWarningsHandler.php'
            - '../src/Core/Domain/Entity'


    App\Core\Application\Service\GenerateWarningsHandler:
        arguments:
            $repositories: !tagged_iterator app.warning_source

    App\Core\Application\Command\:
        resource: '../src/Core/Application/Command'
        tags: ['console.command']
        public: true

    App\Core\Application\Service\:
        resource: '../src/Core/Application/Service/*'
        exclude:
            - '../src/Core/Application/Service/GenerateWarningsHandler.php'

    App\Core\Domain\Repository\:
        resource: '../src/Core/Domain/Repository/*'

    App\Core\Infrastructure\Persistence\Doctrine\:
        resource: '../src/Core/Infrastructure/Persistence/Doctrine/*'

    App\Finance\:
        resource: '../src/Finance/*'
        exclude: '../src/Finance/Domain/Entity'

    App\Finance\Application\Service\:
        resource: '../src/Finance/Application/Service/*'

    App\Finance\Domain\Repository\:
        resource: '../src/Finance/Domain/Repository/*'

    App\Finance\Infrastructure\Persistence\Doctrine\BudgetRepository:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags: ['app.warning_source']

    App\Finance\Infrastructure\Persistence\Doctrine\InvoiceRepository:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags: ['app.warning_source']

    App\Finance\Infrastructure\Persistence\Doctrine\ContractorRepository:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags: ['app.warning_source']

    App\DataFixtures\:
        resource: '../src/DataFixtures'
        tags: ['doctrine.fixture.orm']
